# Generated by Django 3.1.4 on 2021-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_plan',
            field=models.CharField(default='Bronze', max_length=20),
        ),
    ]
