# Generated by Django 3.1.4 on 2021-03-02 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_sub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_date',
            field=models.DateTimeField(default=datetime.date(2021, 3, 2)),
        ),
    ]
