# Generated by Django 3.1.4 on 2021-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210302_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(null=True),
        ),
    ]
