# Generated by Django 3.1.4 on 2021-01-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotUnderstood',
        ),
    ]
