# Generated by Django 3.1.4 on 2021-01-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_delete_notunderstood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
