# Generated by Django 3.1.4 on 2021-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_delete_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='rotation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
