# Generated by Django 3.1.4 on 2021-01-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0004_auto_20210119_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='word',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='scene_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scene',
            name='scene_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='understood',
            name='word',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='pic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonym',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
