# Generated by Django 3.1.4 on 2021-01-26 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenes', '0005_auto_20210126_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='scene_name',
        ),
        migrations.AddField(
            model_name='percentage',
            name='scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage', to='scenes.scene'),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='complete',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='percentage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='total_vocab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
