# Generated by Django 3.1.4 on 2021-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0006_auto_20210126_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='scene',
        ),
        migrations.AddField(
            model_name='percentage',
            name='scene_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
