# Generated by Django 3.1.4 on 2021-02-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0008_pointtoapprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtoapprove',
            name='target_point',
            field=models.IntegerField(default=0),
        ),
    ]
